### ISSUE TITLE
Ufuncs for complex numbers

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#13179]
This is a tracker for a number of requests for making working with complex numbers a bit easier/faster
- [ ] Get just the normalized number `z/|z|` (the [sgn](http://en.wikipedia.org/wiki/Sign_function) function; maybe extend to `copysign`?) (see #3621)
- [ ] Get the power of a complex number `z * z.conj()` (instead of the slow `np.abs(z)**2`). `square` would be logical but is already defined to just do `z*z`... (see #3994)
- [ ] A fast way to get the inverse of `angle`, i.e., `exp(1j * a) = cos(a) + 1j * sin(a)`. Note that for large angle arrays, `exp(1j*a)` needlessly triples memory use for the input (see #5625; somewhat related: `sincos` function, see #2626)
- [ ] Possibly, combined `abs` and `angle` and their inverse, perhaps most logical as part of providing polar to cartesian transformations (see #5228)

**Comment by rkern** [comment]
`numpy.emath` isn't the right place for these. That module is really just for functions which have useful `RR->RR` variants that are the main versions in the `numpy` namespace (e.g. where `np.sqrt(-1)` raises an exception) but where we also want a variant that treats the whole `RR` number line as a subset of the complex numbers `CC` (e.g. where `np.sqrt(-1) == 1j`).

`scipy.special` is the default place where new ufuncs like these should start out.

**Comment by NeilGirdhar** [comment]
@rkern  Makes sense.  What do you think about making an issue like this in the `scipy` repository?

**Comment by mhvk** [comment]
@rkern - sticking to the usual consideration that numpy should just cover the standard C math library, I guess these complex ufuncs indeed do not quite belong in numpy, though especially for `expj`, where one could use the `sincos` built-in, @charris and @juliantaylor were more on the fence (see #5625). Also, the functions requested here would seem a bit odd amidst the bessell functions etc in scipy.special, even though it has a section with [convenience functions](https://docs.scipy.org/doc/scipy/reference/special.html#convenience-functions) *which includes `cbrt` that later moved to numpy).

Looking a bit further afield, base math for julia includes [`abs2`](https://docs.julialang.org/en/v1/base/math/#Base.abs2) and uses `z/|z|` for [`sign`](https://docs.julialang.org/en/v1/base/math/#Base.sign), which is more useful than the strange one used for [`np.sign`]( https://numpy.org/doc/stable/reference/generated/numpy.sign.html)  - see #3621. And in python `cmath.rect` and `cmath.polar` transform to/from complex real/imag and polar representations.

**Comment by rkern** [comment]
I'm not necessarily opposed to some of these making their way into `numpy`'s namespace. But `scipy.special` is going to be where you will face the least resistance to a PR offering these. They do fit within `scipy.special`'s scope.

**Comment by charris** [comment]
TBH, I've often thought an `abs2` would be useful, I've probably needed it as often as `abs`. The definition of `sign` or `sgn` might usefully be addressed in the proposed API document.

**Comment by mhvk** [comment]
`abs2` definitely has come up most often as a request; much use of FFTs at some point involves the power spectrum (aside, @NeilGirdhar, this is why I had it as `power` above before you asked me to change it to the (better) square modulus...). `expj` is particularly helpful also in Fourier analysis, for unequally spaced data. But I may have been looking at radio baseband data too much!

**Comment by mhvk** [comment]
@charris - what is "the proposed API document"?

**Comment by charris** [comment]
@mhvk The array api standard, see #18585.
