### ISSUE TITLE
MAINT: Tracking issue for towncrier usage

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#14112]
Towncrier while working, currently creates somewhat malformed outputs. In principle we can just fix it up manually, but I am working on fixing things upstream as well:

- [ ] Do not enforce bullet point style for segments (there is a manual indent, maybe to support manual wrapping, since jinja2 supports both of these). *(https://github.com/hawkowl/towncrier/pull/158)*
- [ ] Title cannot be a heading with `====` style above and below, becuase the title is not jinja2 templated like the rest. *(https://github.com/hawkowl/towncrier/pull/158)*

There are also the small issue:

- [ ] Incarnation with `--version NumPy` adds an extra space *(Mostly requires fixup for docs, it should be only `--version=1.XX.x`, the name might as well be hardcoded in the template)*
- [ ] The `compatibility` section has a typo. *(fixed on local branch, but that requires towncrier updates)*
- [ ] Move `changelog` folder to a better place, especially since `doc/changelog` exists.

**Comment by seberg** [comment]
Most of this is done (although towncrier master may still need a small fixup).
