### ISSUE TITLE
REL: PRs that may need release notes

### ISSUE THREAD

**Issue by charris** [numpy/numpy#17533]
In order to start preparing for the 1.20.0 I thought I'd check for missing release notes. This is a generated starting list for enhancements, some entries may be spurious and I've omitted the SIMD work which I think falls under performance. I will later add a list for deprecations. I'm thinking we need another tag, maybe `NEW`, to mark true additions.

Enhancements
--------------------
- [x] #13516 ENH: enable multi-platform SIMD compiler optimizations
- [x] #15121 ENH: random: Add the method `permuted` to Generator.
- [x] #15666 ENH: Improved `__str__` for polynomials
- [x] #16134 ENH: Implement concatenate dtype and casting keyword arguments
- [x] #16200 ENH: Rewrite of array-coercion to support new dtypes
- [x] #16476 ENH: add `norm=forward,backward` to numpy.fft functions
- [x] #16515 ENH: add type stubs from numpy-stubs
- [x] #16558 ENH: make typing module available at runtime
- [x] #16570 ENH: Throw TypeError on operator concat on Numpy Arrays
- [x] #16594 ENH: Add __f2py_numpy_version__ attribute to Fortran modules.
- [x] #16650 ENH: Allow genfromtxt to unpack structured arrays
- [x] #16675 ENH: Add support for file like objects to np.core.records.fromfile
- [x] #16710 ENH, BLD: Add RPATH support for AIX
- [x] #16730 ENH: Use f90 compiler specified in f2py command line args for...
- [x] #16986 ENH: Add NumPy declarations to be used by Cython 3.0+
- [x] #17123 ENH: allow running mypy through runtests.py
- [x] #17195 ENH: Make the window functions exactly symmetric
- [x] #17284 ENH: Pass optimizations arguments to asv build
- [x] #17344 ENH, BLD: Support for the NVIDIA HPC SDK nvfortran compiler
- [x] #17456 ENH: add dtype option to numpy.lib.function_base.cov and corrcoef
