### ISSUE TITLE
ENH: Derived type support checklist

### ISSUE THREAD

**Issue by HaoZeke** [numpy/numpy#21160]
### Proposed new feature or change:

Post #20770 there are some points remaining:

- [ ] Scalar numeric types (c_float, c_double)
- [ ] Derived types containing arrays of numeric data
- [ ] Arrays of derived types

The general implementation is to have two separate implementation structures:
- One for the intrinsic types which are defined to map to C structures
- Another, which is possibly more flexible but also slightly more fragile, is the opaque pointer mechanism
