### ISSUE TITLE
ENH: `np.kron` Enhancements Tracking

### ISSUE THREAD

**Issue by ganesh-k13** [numpy/numpy#21257]
## Kronecker Product Enhancements Tracker
`np.kron` lacks a few features and required testing. This GH issue aims to capture all of them in a single place.

### 1. Masked array support
Currently, masked arrays are not supported for `np.kron`
Example:
```python
>>> x = ma.array([[1, 2], [3, 4]], mask=[[0, 1], [1, 0]])
>>> x
masked_array(
  data=[[1, --],
        [--, 4]],
  mask=[[False,  True],
        [ True, False]],
  fill_value=999999)
>>> np.kron(x,x)
masked_array(
  data=[[ 1,  2,  2,  4],
        [ 3,  4,  6,  8],
        [ 3,  6,  4,  8],
        [ 9, 12, 12, 16]],
  mask=False,
  fill_value=999999)
```

### 2. `ValueError` on zero dims
Original issue: #21051
`numpy.kron` function raises an exception `ValueError: need at least one array to concatenate` when first argument has zero dimensionality (either `[0, N]` or `[N, 0]` shape).

Reproduce the code example:

```python
import numpy as np

np.kron(np.zeros([0, 3]), np.zeros([2, 2]))  # raises an exception
np.kron(np.zeros([3, 0]), np.zeros([2, 2]))  # raises an exception
np.kron(np.zeros([3, 3]), np.zeros([0, 2]))  # works perfectly fine
np.kron(np.zeros([3, 3]), np.zeros([2, 0]))  # works perfectly fine
```

### 3. Improve performance of kron
Performance of kron can be improved further. Source: https://stackoverflow.com/questions/56067643/speeding-up-kronecker-products-numpy/56067827#56067827
Brief:
<details>
<summary>Benchmarks</summary>

```
>>> a = np.random.random((60,60))
>>> b = np.random.random((60,60))
```

After #21232 :
```
>>> np.__version__
'1.22.0.dev0+2808.g7916d567f'
>>> timeit.timeit(lambda: np.kron(a, b), number=10)
0.6451533360000212
```
Before:
```
>>> np.__version__
'1.21.2'
>>> timeit.timeit(lambda: np.kron(a, b), number=10)
1.0160858610001924
```
~57% perf improvement.

But there is a better way as per https://stackoverflow.com/a/56067827/5671364
```
>>> timeit.timeit(lambda: np.einsum('ik,jl', a, b).reshape(3600,3600), number=10)
0.3949863890002234
```
</details>

### 4. Improve functional testing
Currently, there are only few test cases covering type checks, dim checks, and basic smoke tests.
Requirement is to have more tests on the functionality of kron

Tracking:
* [x] 1. Masked array support: https://github.com/numpy/numpy/pull/21262
* [x] 2. `ValueError` on zero dims: #21232 
* [x] 3. Improve performance of kron: https://github.com/numpy/numpy/pull/21354
* [x] 4. Improve functional testing

**Comment by mattip** [comment]
@ganesh-k13 can we close this?

**Comment by ganesh-k13** [comment]
> 4. Improve functional testing

This is still left, will pick it up in a while and close it as soon as it's done.

**Comment by ganesh-k13** [comment]
Closing this issue as all the tasks are completed. Thanks!
