### ISSUE TITLE
Install and packaging improvements todo list

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#6599]
After the latest round of install pain and the recent thread "_stop supporting `'setup.py install'`; start requiring `'pip install .'` instead_", it's time to start fixing a few things. Here's a list (ticked items are addressed in gh-6895, which is not merged yet):
- [x] unconditionally import `setuptools` (will fix gh-6551)
- [ ] ~~error on `python setup.py install`. Provide a switch `--force` for `python setup.py install`. Mailing list discussion [here](http://article.gmane.org/gmane.comp.python.numeric.general/61757)~~ not going to fly for now, see [this email about issues](https://mail.scipy.org/pipermail/numpy-discussion/2015-November/074146.html)
- [x] update all install docs
- [x] make it even clearer in big bold letters in the docs that scientific distributions ~~or things like Homebrew~~ are preferred over building from source or even `pip`.
- [x] error on `python setup.py upload` (saying `"use `twine upload -s` instead"`)
- [x] error on `python setup.py upload_docs`
- [x] error on `python setup.py easy_install`
- [x] error on `python setup.py test` (saying `"use `python runtests.py` instead"`)
- [x] remove `setupegg.py`
- [x] error on `python setup.py clean` (saying `"use `git clean -xdf` (or -Xdf ...) instead"`)
- [x] change `python setup.py --help` to first show numpy-specific stuff before setuptools help info
- [x] figure out a ~~better~~ way to test the various methods of installing numpy
  - install from `sdist`
  - install via `bdist_wheel`
  - `easy_install` (is still triggered via `setup_requires`). Note, direct use of `easy_install` by users is not supported - meaning it may work but if it doesn't then don't expect support (use `pip` instead).
    This can be tested by installing a dummy package that uses `setup_requires='numpy'` on TravisCI.
  - the recommended `pip install .`
  - in-place builds (`pip install -e`, `build_ext`, `develop`)
  - builds with `--config xxx build` followed by `pip install .`
  - with and without `virtualenv` (can make a difference)
  - what else?
- [x] when `pip upgrade` is released (should be soon, maybe under a different name, see https://github.com/pypa/pip/pull/3194 and https://github.com/pypa/pip/issues/59), officially change our mind and recommend the use of `install_requires` to packages depending on numpy.
- [x] figure out what to do about `setup_requires` (`pip` won't support that any time soon)
- [ ] fix up the metadata. now `sdist` overwrites "author" with "maintainer". Consider using `setup.cfg` or a new static metadata format that may materialize soon.
- [x] do a check on version numbering correctness (see [https://github.com/numpy/numpy/issues/6431#issuecomment-147112731) and make `np.lib.NumpyVersion` accessible in `numpy.version`
- [x] figure out what to do with `bdist_egg`, `bdist_rpm`, `bdist_mpkg`, etc. RPM is probably a valid format to generate, the rest we may want to put behind a `--force` flag at least.
- [x] do we need to provide a `conda` build recipe? --> EDIT: no, leave this to `conda-forge`

For interested people needing a bit of context, the [Python Packaging User Guide](https://packaging.python.org/en/latest/) is the authoritative doc about Python packaging in general.

**Comment by rgommers** [comment]
Because this is such a popular thing to work on and we'd like to avoid double work: post a comment if you're working on something:)

**Comment by matthew-brett** [comment]
I don't agree that homebrew is a good replacement for pip install on Mac.  Although homebrew is generally very good, I don't use it for Python packages, except occasionally for very difficult ones like Python VTK.

In general, pip works very well on Mac.  For example, I would expect this to always work on Mac:

```
pip install numpy scipy matplotlib pandas scikit-image scikit-learn
```

That takes about a minute on my laptop.  I think we should continue (as a community) to make sure that works.  I personally use that as my only install method on OSX.

**Comment by rgommers** [comment]
@matthew-brett you have a good point I think. I do use Homebrew to install Python and gfortran, but install everything from source (or with pip). The main problem is Windows. And compiling on OS X - that should really be avoided (so current situation with wheels is great).

**Comment by matthew-brett** [comment]
Right - I think that's probably the ideal for homebrew (use for installing,
libraries, Python, but not Python packages).

**Comment by rgommers** [comment]
Good, we agree - let's just phrase it exactly like that in the docs then.

**Comment by rgommers** [comment]
PR: gh-6895. I'll tick the items in the summary that are addressed by that PR.

**Comment by rgommers** [comment]
Here is an overview of where we keep install info:

- [INSTALL.txt](https://github.com/numpy/numpy/blob/master/INSTALL.txt)
- [Numpy developer guide](http://docs.scipy.org/doc/numpy-dev/dev/development_environment.html)
- [Numpy User Guide](http://docs.scipy.org/doc/numpy-dev/user/install.html), has a [building from source](http://docs.scipy.org/doc/numpy-dev/user/building.html) section
- http://scipy.org/install.html (top-level page for Scipy Stack)
- And [here](http://scipy.org/scipylib/building/index.html) are detailed build instructions on scipy.org

**Comment by mattip** [comment]
@rgommers are there still relevant items on the checklist?

**Comment by rgommers** [comment]
Yes there are. I've ticked one off, the rest is still relevant. `pip upgrade`, PEP517/518 etc. is still not a done deal.

**Comment by mattip** [comment]
`pip upgrade` has been rejected it seems, the relevant issue and PR you linked to are closed. 

The issue of `setup_requires` came up again on a discussion forum, I turned it into an issue astrofrog/fast-histogram#34. Do we have a better solution than requiring the SciPy fix scipy/scipy#3566 for downstream packages?

**Comment by rgommers** [comment]
> `pip upgrade` has been rejected it seems, the relevant issue and PR you linked to are closed.

It's actually better, rather then introducing a new name the default behavior of `pip install -U` has been changed from "eager" to "as needed". So that's all good.

> The issue of `setup_requires` came up again on a discussion forum

That's a clear bug in `fast-histogram`. `setup_requires` is the problematic one, `install_requires` is fine nowadays.

**Comment by mattip** [comment]
According to the [original report](https://gitter.im/numpy/numpy?at=5c311fa6357dd7655d21c982) I think `setup_requires` does not install the package into python, it only does a local build-from-source which then is not available after the setup step.

**Comment by mattip** [comment]
Thanks for checking, indeed they already have `install_requires`

**Comment by mattip** [comment]
We still support easy_install (and use it in `doc/Makefile`) even though it has [`been deprecated`](https://setuptools.readthedocs.io/en/latest/easy_install.html). Should we remove support for it?

**Comment by rgommers** [comment]
From the checklist: `easy_install` (is still triggered via `setup_requires`). Note, direct use of `easy_install` by users is not supported - meaning it may work but if it doesn't then don't expect support (use `pip` instead).

If you mean by "remove support for it" to give a hard error when anyone says `easy_install numpy` or when it's invoked by `setuptools` itself, then definitely no. That will break a lot of things for no real-world gain.

**Comment by rgommers** [comment]
This is all basically done, let's close this.
